ALTER TABLE "CompanySettings"
  ADD COLUMN IF NOT EXISTS "systemName" TEXT NOT NULL DEFAULT 'Sistema OS',
  ADD COLUMN IF NOT EXISTS "primaryColor" TEXT NOT NULL DEFAULT '#245dde',
  ADD COLUMN IF NOT EXISTS "sidebarColor" TEXT NOT NULL DEFAULT '#12233e';
